project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - intro.qmd
  - python_geospatial_basics.qmd
  - R_geospatial_basics.qmd
  - Xarray.qmd
  - pdal.qmd
  - python-pdal.qmd
self_contained: true
theme: blood
