name: geo
channels:
  - defaults
  - conda-forge
dependencies: 
  - contextily
  - geodatasets
  - geopandas
  - jupyterlab
  - nc-time-axis
  - pythia_datasets
  - rioxarray
  - tabulate
  - tqdm
  
