<!DOCTYPE html>
<html lang="en"><head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <title>Python Lectures</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #f8f8f2;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #f8f8f2; } /* Normal */
    code span.al { color: #f07178; background-color: #2a0f15; font-weight: bold; } /* Alert */
    code span.an { color: #d4d0ab; } /* Annotation */
    code span.at { color: #00e0e0; } /* Attribute */
    code span.bn { color: #d4d0ab; } /* BaseN */
    code span.bu { color: #abe338; } /* BuiltIn */
    code span.cf { color: #ffa07a; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #abe338; } /* Char */
    code span.cn { color: #ffd700; } /* Constant */
    code span.co { color: #f8f8f2; font-style: italic; } /* Comment */
    code span.cv { color: #ffd700; } /* CommentVar */
    code span.do { color: #f8f8f2; } /* Documentation */
    code span.dt { color: #ffa07a; } /* DataType */
    code span.dv { color: #d4d0ab; } /* DecVal */
    code span.er { color: #f07178; text-decoration: underline; } /* Error */
    code span.ex { color: #00e0e0; font-weight: bold; } /* Extension */
    code span.fl { color: #d4d0ab; } /* Float */
    code span.fu { color: #ffa07a; } /* Function */
    code span.im { color: #abe338; } /* Import */
    code span.in { color: #d4d0ab; } /* Information */
    code span.kw { color: #ffa07a; font-weight: bold; } /* Keyword */
    code span.op { color: #ffa07a; } /* Operator */
    code span.ot { color: #00e0e0; } /* Other */
    code span.pp { color: #dcc6e0; } /* Preprocessor */
    code span.re { color: #00e0e0; background-color: #f8f8f2; } /* RegionMarker */
    code span.sc { color: #abe338; } /* SpecialChar */
    code span.ss { color: #abe338; } /* SpecialString */
    code span.st { color: #abe338; } /* String */
    code span.va { color: #00e0e0; } /* Variable */
    code span.vs { color: #abe338; } /* VerbatimString */
    code span.wa { color: #dcc6e0; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-0d84831d95dedbd79f53d1a65782b16f.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
  
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Python Lectures</h1>

<div class="quarto-title-authors">
</div>

</section>
<section>
<section id="introducing-python" class="title-slide slide level1 center">
<h1>Introducing Python</h1>
<ul>
<li>It allows for more flexibility than a GUI based GIS program.</li>
<li>Other GIS applications (e.g.&nbsp;QGIS, ArcGIS, postGIS) often have a Python interface.</li>
<li>generally a widely used language.</li>
</ul>
</section>
<section id="environment" class="slide level2 scrollable smaller non-incremental">
<h2>Environment</h2>
<p>Before we get started we need to set up a Python environment in which to work. We will be using Anaconda for this. It <em>should</em> already be installed on the lab computers. If you are using your own computer</p>
<ul>
<li>Download the environment.yml</li>
<li>If you are working on a lab computer In the start menu search for Anaconda. Open an Anaconda Powershell. (on linux or mac with Anconda or miniconda or Mamba installed just open a terminal)(If you are installing on your own computer I recommend <a href="https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html">Mamba</a>)</li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource {bash} number-lines code-with-copy"><code class="sourceCode"><span id="cb1-1"><a></a>cd ~</span>
<span id="cb1-2"><a></a>mkdir geog441</span>
<span id="cb1-3"><a></a>cd geog441</span>
<span id="cb1-4"><a></a>cp ~/Downloads/environment.yml .</span>
<span id="cb1-5"><a></a>conda env create -f environment.yml</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>What is this <em>environment.yml</em> thing?</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource {yml} number-lines code-with-copy"><code class="sourceCode"><span id="cb2-1"><a></a>name: geo</span>
<span id="cb2-2"><a></a>channels:</span>
<span id="cb2-3"><a></a>  - defaults</span>
<span id="cb2-4"><a></a>dependencies: </span>
<span id="cb2-5"><a></a>  - geopandas</span>
<span id="cb2-6"><a></a>  - jupyterlab</span>
<span id="cb2-7"><a></a>  - rioxarray</span>
<span id="cb2-8"><a></a>  - tabulate</span>
<span id="cb2-9"><a></a>  - tqdm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Using <code>conda env create</code> with the environment yaml creates a new conda environment named <em>geo</em> with the dependencies installed. Next we will activate the <em>geo</em> environment.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource {bash} number-lines code-with-copy"><code class="sourceCode"><span id="cb3-1"><a></a>conda activate geo</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Notice that the conda environment shown after the prompt has changed from <code>(base)</code> to <code>(geo)</code>.</p>
<p>If later you find that you need another package you can add it to the environment (while in the environment) with <code>conda install &lt;whatever_package&gt;</code>.</p>
<p><a href="https://docs.conda.io/projects/conda/en/4.6.0/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file">More info on managing conda environments</a></p>
</section>
<section id="starting-a-jupyter-lab" class="slide level2">
<h2>Starting a Jupyter Lab</h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource {bash} number-lines code-with-copy"><code class="sourceCode"><span id="cb4-1"><a></a>jupyter lab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This will open a new jupyter lab in your browser.</p>
</section>
<section id="using-vscode" class="slide level2">
<h2>Using VScode</h2>
<p>Running Jupyter in VScode offers some advantages (in my opinion). To do this you need to install the jupyter extension and the Python Extension. Then when you open a file with a .ipynb extension it will be treated as a Jupyter notebook.</p>
</section>
<section id="basic-python-data-types" class="slide level2 scrollable">
<h2>Basic Python data types</h2>
<table class="caption-top">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Example(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>String</td>
<td><code>'Dude!'</code></td>
</tr>
<tr class="even">
<td>Float</td>
<td><code>1.2</code></td>
</tr>
<tr class="odd">
<td>Int</td>
<td><code>3</code></td>
</tr>
<tr class="even">
<td>Tuple</td>
<td><code>('x', 'y')</code><br><code>(1, 2)</code><br><code>('x', 3.2)</code></td>
</tr>
<tr class="odd">
<td>List</td>
<td><code>['x', 'y']</code><br><code>[1, 2]</code><br>Possible but bad –&gt; <code>['x', 3.2]</code></td>
</tr>
<tr class="even">
<td>Dict</td>
<td><code>{'dogs': 26, 'cats', 100}</code></td>
</tr>
<tr class="odd">
<td>etc…</td>
<td>there are others</td>
</tr>
</tbody>
</table>
</section>
<section id="basic-numbers" class="slide level2">
<h2>Basic Numbers</h2>
<p>Floats and Ints don’t do anything all that surprising</p>
<div id="11fb095b" class="cell columns column-output-location" data-execution_count="1">
<div class="column">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a></a>a <span class="op">=</span> <span class="dv">2</span> <span class="op">+</span> <span class="dv">2</span></span>
<span id="cb5-2"><a></a>b <span class="op">=</span> <span class="fl">2.0</span> <span class="op">+</span> <span class="fl">2.0</span></span>
<span id="cb5-3"><a></a>c <span class="op">=</span> a <span class="op">+</span> b</span>
<span id="cb5-4"><a></a></span>
<span id="cb5-5"><a></a></span>
<span id="cb5-6"><a></a><span class="bu">print</span>(<span class="ss">f'a is an </span><span class="sc">{</span><span class="bu">type</span>(a)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-7"><a></a><span class="bu">print</span>(<span class="ss">f'b is a </span><span class="sc">{</span><span class="bu">type</span>(b)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-8"><a></a><span class="bu">print</span>(<span class="ss">f'c is a </span><span class="sc">{</span><span class="bu">type</span>(c)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-9"><a></a><span class="bu">print</span>(<span class="ss">f'a / b is </span><span class="sc">{</span>a <span class="op">/</span> b<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-10"><a></a><span class="bu">print</span>(<span class="ss">f'5 / 4 is </span><span class="sc">{</span><span class="dv">5</span> <span class="op">/</span> <span class="dv">4</span><span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-11"><a></a><span class="bu">print</span>(<span class="ss">f'but 5 // 4 is </span><span class="sc">{</span><span class="dv">5</span> <span class="op">//</span> <span class="dv">4</span><span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-12"><a></a><span class="bu">print</span>(<span class="ss">f'and 5 % 4 is </span><span class="sc">{</span><span class="dv">5</span> <span class="op">%</span> <span class="dv">4</span><span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>a is an &lt;class 'int'&gt;
b is a &lt;class 'float'&gt;
c is a &lt;class 'float'&gt;
a / b is 1.0
5 / 4 is 1.25
but 5 // 4 is 1
and 5 % 4 is 1</code></pre>
</div>
</div></div>
</section>
<section id="exercise---basic-numbers" class="slide level2" data-background="#FF007F">
<h2>Exercise - Basic Numbers</h2>
<p>Try the following, print the results, see what they do.</p>
<div id="593f48e1" class="cell columns column-output-location" data-execution_count="2">
<div class="column">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a></a>a <span class="op">=</span> <span class="dv">5</span> <span class="op">//</span> <span class="dv">4</span></span>
<span id="cb7-2"><a></a>b <span class="op">=</span> <span class="dv">5</span> <span class="op">%</span> <span class="dv">4</span></span>
<span id="cb7-3"><a></a>c <span class="op">=</span> a <span class="op">+</span> b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">

</div></div>
</section>
<section id="sequences" class="slide level2">
<h2>Sequences</h2>
<p>Lists, tuples, and strings ae all sequences</p>
<div id="1cd903cf" class="cell columns column-output-location" data-execution_count="3">
<div class="column">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a></a><span class="co"># a list</span></span>
<span id="cb8-2"><a></a>a_list <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>]</span>
<span id="cb8-3"><a></a></span>
<span id="cb8-4"><a></a><span class="co"># a tuple</span></span>
<span id="cb8-5"><a></a>a_tup <span class="op">=</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>)</span>
<span id="cb8-6"><a></a></span>
<span id="cb8-7"><a></a><span class="co"># a string</span></span>
<span id="cb8-8"><a></a>a_str <span class="op">=</span> <span class="st">'Wil je graag een neushorn?'</span></span>
<span id="cb8-9"><a></a></span>
<span id="cb8-10"><a></a><span class="co"># access by index</span></span>
<span id="cb8-11"><a></a>a <span class="op">=</span> a_list[<span class="dv">0</span>]</span>
<span id="cb8-12"><a></a>b <span class="op">=</span> a_list[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb8-13"><a></a>c <span class="op">=</span> a_list[<span class="dv">4</span>]</span>
<span id="cb8-14"><a></a><span class="bu">print</span>(<span class="ss">f'by index:</span><span class="ch">\n</span><span class="ss"> 0 --&gt; </span><span class="sc">{</span>a<span class="sc">}</span><span class="ss">,</span><span class="ch">\n</span><span class="ss">-1 --&gt; </span><span class="sc">{</span>b<span class="sc">}</span><span class="ss">,</span><span class="ch">\n</span><span class="ss"> 4 --&gt; </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-15"><a></a></span>
<span id="cb8-16"><a></a><span class="co"># works fro strings to</span></span>
<span id="cb8-17"><a></a><span class="bu">print</span>(<span class="st">'string item at 4 --&gt; '</span>, a_str[<span class="dv">4</span>])</span>
<span id="cb8-18"><a></a></span>
<span id="cb8-19"><a></a><span class="co"># you can slice a list or tuple(remember 0 indexed)</span></span>
<span id="cb8-20"><a></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">slices:'</span>)</span>
<span id="cb8-21"><a></a><span class="bu">print</span>(a_list[<span class="dv">2</span>:<span class="dv">5</span>])</span>
<span id="cb8-22"><a></a><span class="bu">print</span>(a_list[<span class="dv">8</span>:])</span>
<span id="cb8-23"><a></a><span class="bu">print</span>(a_tup[<span class="dv">2</span>:<span class="dv">5</span>])</span>
<span id="cb8-24"><a></a><span class="bu">print</span>(a_str[<span class="op">-</span><span class="dv">9</span>:])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>by index:
 0 --&gt; 1,
-1 --&gt; 9,
 4 --&gt; 5
string item at 4 --&gt;  j

slices:
[3, 4, 5]
[9]
(3, 4, 5)
neushorn?</code></pre>
</div>
</div></div>
<p><a href="https://www.geeksforgeeks.org/python-list-slicing/#">Slicing</a><br>
<a href="https://labex.io/tutorials/python-how-to-manipulate-list-sequences-in-python-419858">Sequences tutorial</a><br>
<a href="https://www.youtube.com/watch?v=n3KMrwmq_94">Sequence tutorial as video</a></p>
</section>
<section id="exercise---lists-and-tuples" class="slide level2" data-background="#FF007F">
<h2>Exercise - Lists and Tuples</h2>
<p>The key between lists and tuples is that tuples are immutable. Try assigning a value to both of the following.</p>
<div id="f50781a1" class="cell columns column-output-location" data-execution_count="4">
<div class="column">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a></a><span class="co"># a list</span></span>
<span id="cb10-2"><a></a>a_list <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>]</span>
<span id="cb10-3"><a></a></span>
<span id="cb10-4"><a></a><span class="co"># a tuple</span></span>
<span id="cb10-5"><a></a>a_tup <span class="op">=</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">

</div></div>
</section>
<section id="dictionaries" class="slide level2">
<h2>Dictionaries</h2>
<div id="a8e58767" class="cell columns column-output-location" data-execution_count="5">
<div class="column">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a></a>pets <span class="op">=</span> {<span class="st">'honden'</span>: <span class="dv">26</span>, <span class="st">'katten'</span>: <span class="dv">100</span>}</span>
<span id="cb11-2"><a></a></span>
<span id="cb11-3"><a></a><span class="cf">for</span> key, val <span class="kw">in</span> pets.items():</span>
<span id="cb11-4"><a></a>  <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>val<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>key<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb11-5"><a></a></span>
<span id="cb11-6"><a></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>pets[<span class="st">"honden"</span>] <span class="op">+</span> pets[<span class="st">"katten"</span>]<span class="sc">}</span><span class="ss"> huisdieren'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>26 honden
100 katten
126 huisdieren</code></pre>
</div>
</div></div>
<p><a href="https://www.w3schools.com/python/python_dictionaries.asp">More on dictionaries</a></p>
</section>
<section id="iterating" class="slide level2">
<h2>Iterating</h2>
<div id="21dd5aac" class="cell columns column-output-location" data-execution_count="6">
<div class="column">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a></a>a <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>]</span>
<span id="cb13-2"><a></a></span>
<span id="cb13-3"><a></a><span class="co"># use a loop to append squared values to new lists</span></span>
<span id="cb13-4"><a></a>b <span class="op">=</span> []</span>
<span id="cb13-5"><a></a><span class="cf">for</span> n <span class="kw">in</span> a:</span>
<span id="cb13-6"><a></a>  b.append(n<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb13-7"><a></a></span>
<span id="cb13-8"><a></a><span class="co"># or, better, use a comprehension</span></span>
<span id="cb13-9"><a></a>c <span class="op">=</span> [n<span class="op">**</span><span class="dv">2</span> <span class="cf">for</span> n <span class="kw">in</span> a]</span>
<span id="cb13-10"><a></a></span>
<span id="cb13-11"><a></a><span class="bu">print</span>(b)</span>
<span id="cb13-12"><a></a><span class="bu">print</span>(<span class="st">'is the same as'</span>)</span>
<span id="cb13-13"><a></a><span class="bu">print</span>(c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>[1, 4, 9, 16, 25, 36, 49, 64, 81]
is the same as
[1, 4, 9, 16, 25, 36, 49, 64, 81]</code></pre>
</div>
</div></div>
</section>
<section id="exercise---iterating" class="slide level2" data-background="#FF007F">
<h2>Exercise - Iterating</h2>
<p>You can nest loops.</p>
<div id="33148a44" class="cell columns column-output-location" data-execution_count="7">
<div class="column">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a></a>numbers <span class="op">=</span> []</span>
<span id="cb15-2"><a></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb15-3"><a></a>  <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb15-4"><a></a>    numbers.append((i, j))</span>
<span id="cb15-5"><a></a></span>
<span id="cb15-6"><a></a>numbers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]</code></pre>
</div>
</div></div>
<ul>
<li>Recreate the above with a list comprehension.</li>
<li>replace the square brackets in this list comprehension, <code>= [n**2 for n in a]</code>, with parenthesis.</li>
<li>Can you create a dictionary with a comprehension.</li>
</ul>
</section>
<section id="functions" class="slide level2 scrollable smaller non-incremental">
<h2>Functions</h2>
<ul>
<li>Defined with def</li>
<li>Can take arguments</li>
<li>can return something</li>
<li>have there own scope</li>
</ul>
<div id="ba4a7ee6" class="cell columns column-output-location" data-execution_count="8">
<div class="column">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb17-2"><a></a></span>
<span id="cb17-3"><a></a><span class="kw">def</span> root_mean_square(list_of_numbers):</span>
<span id="cb17-4"><a></a>  rms <span class="op">=</span> np.sqrt(</span>
<span id="cb17-5"><a></a>    np.array([n<span class="op">**</span><span class="dv">2</span> <span class="cf">for</span> n <span class="kw">in</span> list_of_numbers]).<span class="bu">sum</span>() <span class="op">/</span></span>
<span id="cb17-6"><a></a>    <span class="bu">len</span>(list_of_numbers)</span>
<span id="cb17-7"><a></a>    )</span>
<span id="cb17-8"><a></a></span>
<span id="cb17-9"><a></a>  <span class="cf">return</span> rms</span>
<span id="cb17-10"><a></a></span>
<span id="cb17-11"><a></a>l <span class="op">=</span> [<span class="fl">1.2</span>, <span class="fl">3.3</span>, <span class="fl">1.4</span>, <span class="fl">1.4</span>, <span class="fl">4.2</span>]</span>
<span id="cb17-12"><a></a>rms <span class="op">=</span> root_mean_square(l)</span>
<span id="cb17-13"><a></a></span>
<span id="cb17-14"><a></a><span class="bu">print</span>(rms)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>2.6034592372457075</code></pre>
</div>
</div></div>
<p>They do not have to have arguments or return stuff.</p>
<div id="1fe39268" class="cell columns column-output-location" data-execution_count="9">
<div class="column">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a></a><span class="kw">def</span> complain():</span>
<span id="cb19-2"><a></a>  <span class="bu">print</span>(<span class="st">'This is boring!</span><span class="ch">\n</span><span class="st">when will we get to the GIS stuff.</span><span class="ch">\n\U0001F620\U0001F620\U0001F620\n\n</span><span class="st">Soon! Bear with me.'</span>)</span>
<span id="cb19-3"><a></a></span>
<span id="cb19-4"><a></a>complain()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>This is boring!
when will we get to the GIS stuff.
😠😠😠

Soon! Bear with me.</code></pre>
</div>
</div></div>
<p>Python is an <em>object oriented</em> programming language. Everything that you can assign to a variable (which is almost everything) can be though of as an object, for example, built in functions are objects.</p>
<div id="f2aba62b" class="cell columns column-output-location" data-execution_count="10">
<div class="column">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a></a>zzz <span class="op">=</span> <span class="bu">print</span></span>
<span id="cb21-2"><a></a>zzz(<span class="st">'toenails'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>toenails</code></pre>
</div>
</div></div>
<p>Many objects have built in functions as an attribute, these are called methods. For instance, strings have a method called split (they have many other methods as well).</p>
<div id="a250bbef" class="cell columns column-output-location" data-execution_count="11">
<div class="column">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a></a>s <span class="op">=</span> <span class="st">'hyphens-are-everywhere-they-haunt-me-in-my-dreams'</span></span>
<span id="cb23-2"><a></a>s.split(<span class="st">'-'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>['hyphens', 'are', 'everywhere', 'they', 'haunt', 'me', 'in', 'my', 'dreams']</code></pre>
</div>
</div></div>
<p>We will encounter heaps of methods later.</p>
</section>
<section id="exercise---functions" class="slide level2" data-background="#FF007F">
<h2>Exercise - Functions</h2>
<p>Use a function and a list comprehension to reproduce the results of the for loop below:</p>
<div id="0f494db5" class="cell columns column-output-location" data-execution_count="12">
<div class="column">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a></a>l <span class="op">=</span> [(<span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>), (<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>), (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)]</span>
<span id="cb25-2"><a></a></span>
<span id="cb25-3"><a></a>results <span class="op">=</span> []</span>
<span id="cb25-4"><a></a></span>
<span id="cb25-5"><a></a><span class="cf">for</span> t <span class="kw">in</span> l:</span>
<span id="cb25-6"><a></a>  results.append(</span>
<span id="cb25-7"><a></a>    t[<span class="dv">0</span>] <span class="op">+</span> t[<span class="dv">1</span>] <span class="op">-</span> t[<span class="dv">2</span>] <span class="op">+</span></span>
<span id="cb25-8"><a></a>    (t[<span class="dv">0</span>] <span class="op">*</span> t[<span class="dv">1</span>] <span class="op">+</span> t[<span class="dv">2</span>])<span class="op">**</span>t[<span class="dv">1</span>] <span class="op">/</span></span>
<span id="cb25-9"><a></a>    (t[<span class="dv">1</span>]<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> <span class="dv">5</span><span class="op">**</span>t[<span class="dv">0</span>])</span>
<span id="cb25-10"><a></a>  )</span>
<span id="cb25-11"><a></a></span>
<span id="cb25-12"><a></a>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>[5.487822222222222, 2.36, 1.25]</code></pre>
</div>
</div></div>
<p>Take some time to contemplate, what is this?</p>
<div id="ac331aeb" class="cell columns column-output-location" data-execution_count="13">
<div class="column">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb27-2"><a></a></span>
<span id="cb27-3"><a></a>nested_list <span class="op">=</span> [[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>], [<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>], [<span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>]]</span>
<span id="cb27-4"><a></a></span>
<span id="cb27-5"><a></a>np.array(nested_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])</code></pre>
</div>
</div></div>
<p>BTW, you can import a library as anything you want</p>
<div id="8ad392e8" class="cell columns column-output-location" data-execution_count="14">
<div class="column">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a></a><span class="im">import</span> numpy <span class="im">as</span> frogz_on_crack</span>
<span id="cb29-2"><a></a></span>
<span id="cb29-3"><a></a>frogz_on_crack.array([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>array([1, 2, 3])</code></pre>
</div>
</div></div>
<p>Why would one avoid doing this kind of thing?</p>
<p>You can also dump all of the objects from a module into the main namespace</p>
<div id="504379e5" class="cell columns column-output-location" data-execution_count="15">
<div class="column">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a></a><span class="co"># from numpy import everything</span></span>
<span id="cb31-2"><a></a><span class="im">from</span> numpy <span class="im">import</span> <span class="op">*</span></span>
<span id="cb31-3"><a></a></span>
<span id="cb31-4"><a></a>array([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span> ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>array([1, 2, 3])</code></pre>
</div>
</div></div>
<p>Why is this a bad practice? What Is a namespace</p>
<div id="3bd56771" class="cell columns column-output-location" data-execution_count="16">
<div class="column">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a></a>x <span class="op">=</span> <span class="st">'I love </span><span class="ch">\U0001F30D</span><span class="st">'</span></span>
<span id="cb33-2"><a></a></span>
<span id="cb33-3"><a></a><span class="kw">def</span> print_wrapper():</span>
<span id="cb33-4"><a></a>    <span class="bu">print</span>(x)</span>
<span id="cb33-5"><a></a></span>
<span id="cb33-6"><a></a><span class="kw">def</span> print_poo():</span>
<span id="cb33-7"><a></a>    x <span class="op">=</span> <span class="st">'This is the value of x within the function'</span></span>
<span id="cb33-8"><a></a>    <span class="bu">print</span>(x)</span>
<span id="cb33-9"><a></a></span>
<span id="cb33-10"><a></a>print_wrapper()</span>
<span id="cb33-11"><a></a>print_poo()</span>
<span id="cb33-12"><a></a></span>
<span id="cb33-13"><a></a><span class="bu">print</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>I love 🌍
This is the value of x within the function
I love 🌍</code></pre>
</div>
</div></div>
</section>
<section id="pandas-dataframe" class="slide level2 smaller scrollable">
<h2>Pandas DataFrame</h2>
<p>DataFrames hold tabular data. Here we will read a csv file as a DataFrame and mess with it.</p>
<ol type="1">
<li>This cell just downloads the file from a url. <strong>Take a few minutes and see if you can change it to be generally useful</strong> by allowing the url and save location to be specified as arguments. Hint, you need to change very little, and you don’t really need to know how the function works in any detail.</li>
</ol>
<div id="2804f800" class="cell columns column-output-location" data-execution_count="17">
<div class="column">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a></a><span class="im">import</span> requests</span>
<span id="cb35-2"><a></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb35-3"><a></a></span>
<span id="cb35-4"><a></a><span class="kw">def</span> get_NZ_file():</span>
<span id="cb35-5"><a></a>  <span class="co">'''</span></span>
<span id="cb35-6"><a></a><span class="co">  A purposefully bad function to download one specific file.</span></span>
<span id="cb35-7"><a></a><span class="co">  '''</span></span>
<span id="cb35-8"><a></a>  <span class="co"># url to Dec 2024 NZ GH emissions by industry (long url!)</span></span>
<span id="cb35-9"><a></a>  url <span class="op">=</span> <span class="st">'https://www.stats.govt.nz/assets/Uploads/Greenhouse-gas-emissions-industry-and-household/Greenhouse-gas-emissions-industry-and-household-December-2024-quarter/Download-data/greenhouse-gas-emissions-industry-and-household-december-2024-quarter.csv'</span></span>
<span id="cb35-10"><a></a>  <span class="co"># make a dir for data, if does not exist</span></span>
<span id="cb35-11"><a></a>  save_dir <span class="op">=</span> Path.cwd() <span class="op">/</span> <span class="st">'data'</span></span>
<span id="cb35-12"><a></a>  save_dir.mkdir(exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb35-13"><a></a>  <span class="co"># get file name</span></span>
<span id="cb35-14"><a></a>  basename <span class="op">=</span> url.split(<span class="st">'/'</span>)[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb35-15"><a></a>  <span class="co"># and a directory to save to </span></span>
<span id="cb35-16"><a></a>  save_path <span class="op">=</span> save_dir <span class="op">/</span> basename</span>
<span id="cb35-17"><a></a></span>
<span id="cb35-18"><a></a>  <span class="cf">try</span>:</span>
<span id="cb35-19"><a></a>      response <span class="op">=</span> requests.get(url, stream<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb35-20"><a></a>      <span class="co"># raise HTTPError for bad responses (4xx or 5xx)</span></span>
<span id="cb35-21"><a></a>      response.raise_for_status() </span>
<span id="cb35-22"><a></a>      <span class="cf">with</span> <span class="bu">open</span>(save_path, <span class="st">'wb'</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb35-23"><a></a>        <span class="cf">for</span> chunk <span class="kw">in</span> response.iter_content(chunk_size<span class="op">=</span><span class="dv">8192</span>):</span>
<span id="cb35-24"><a></a>          <span class="bu">file</span>.write(chunk)</span>
<span id="cb35-25"><a></a>      <span class="bu">print</span>(<span class="ss">f"File downloaded successfully to </span><span class="sc">{</span>save_path<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb35-26"><a></a></span>
<span id="cb35-27"><a></a>  <span class="cf">except</span> requests.exceptions.RequestException <span class="im">as</span> e:</span>
<span id="cb35-28"><a></a>    <span class="bu">print</span>(<span class="ss">f'An error occurred: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb35-29"><a></a>  <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb35-30"><a></a>    <span class="bu">print</span>(<span class="ss">f'An unexpected error occurred: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb35-31"><a></a></span>
<span id="cb35-32"><a></a>  <span class="cf">return</span> save_path</span>
<span id="cb35-33"><a></a></span>
<span id="cb35-34"><a></a>file_path <span class="op">=</span> get_NZ_file()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>File downloaded successfully to /home/michael/Work/geog441/data/greenhouse-gas-emissions-industry-and-household-december-2024-quarter.csv</code></pre>
</div>
</div></div>
<ol start="2" type="1">
<li>Read the csv, and look at the head (first few rows). Notice that there are column names, and on the left side there is a numerical index.</li>
</ol>
<div id="5861e04d" class="cell columns column-output-location" data-execution_count="18">
<div class="column">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb37-2"><a></a></span>
<span id="cb37-3"><a></a>df <span class="op">=</span> pd.read_csv(file_path)</span>
<span id="cb37-4"><a></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="18">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Anzsic</th>
<th data-quarto-table-cell-role="th">Anzsic_descriptor</th>
<th data-quarto-table-cell-role="th">Gas</th>
<th data-quarto-table-cell-role="th">Period</th>
<th data-quarto-table-cell-role="th">Data_value</th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Units</th>
<th data-quarto-table-cell-role="th">Magnitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.03</td>
<td>10875</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.06</td>
<td>11003</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.09</td>
<td>10993</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.12</td>
<td>10914</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2011.03</td>
<td>11014</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></div>
<p>We can also see the last few rows if we want.</p>
<div id="8b75ad42" class="cell columns column-output-location" data-execution_count="19">
<div class="column">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a></a>df.tail()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="19">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Anzsic</th>
<th data-quarto-table-cell-role="th">Anzsic_descriptor</th>
<th data-quarto-table-cell-role="th">Gas</th>
<th data-quarto-table-cell-role="th">Period</th>
<th data-quarto-table-cell-role="th">Data_value</th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Units</th>
<th data-quarto-table-cell-role="th">Magnitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4795</td>
<td>ZZZ</td>
<td>Total</td>
<td>Nitrous oxide</td>
<td>2023.12</td>
<td>1708</td>
<td>Actual</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4796</td>
<td>ZZZ</td>
<td>Total</td>
<td>Nitrous oxide</td>
<td>2024.03</td>
<td>1615</td>
<td>Actual</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4797</td>
<td>ZZZ</td>
<td>Total</td>
<td>Nitrous oxide</td>
<td>2024.06</td>
<td>1482</td>
<td>Actual</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4798</td>
<td>ZZZ</td>
<td>Total</td>
<td>Nitrous oxide</td>
<td>2024.09</td>
<td>1652</td>
<td>Actual</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4799</td>
<td>ZZZ</td>
<td>Total</td>
<td>Nitrous oxide</td>
<td>2024.12</td>
<td>1662</td>
<td>Actual</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></div>
<p>Or we can slice from the middle using index slicing, just like with a list.</p>
<div id="c87a508e" class="cell columns column-output-location" data-execution_count="20">
<div class="column">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a></a>df[<span class="dv">100</span>:<span class="dv">105</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="20">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Anzsic</th>
<th data-quarto-table-cell-role="th">Anzsic_descriptor</th>
<th data-quarto-table-cell-role="th">Gas</th>
<th data-quarto-table-cell-role="th">Period</th>
<th data-quarto-table-cell-role="th">Data_value</th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Units</th>
<th data-quarto-table-cell-role="th">Magnitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">100</td>
<td>BB1</td>
<td>Mining</td>
<td>Carbon dioxide equivalents</td>
<td>2020.03</td>
<td>307</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">101</td>
<td>BB1</td>
<td>Mining</td>
<td>Carbon dioxide equivalents</td>
<td>2020.06</td>
<td>256</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">102</td>
<td>BB1</td>
<td>Mining</td>
<td>Carbon dioxide equivalents</td>
<td>2020.09</td>
<td>280</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">103</td>
<td>BB1</td>
<td>Mining</td>
<td>Carbon dioxide equivalents</td>
<td>2020.12</td>
<td>271</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">104</td>
<td>BB1</td>
<td>Mining</td>
<td>Carbon dioxide equivalents</td>
<td>2021.03</td>
<td>276</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></div>
<p>There are many other <a href="https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html">ways to select from Pandas DataFrames</a>.</p>
<p>The <code>Period</code> column gives dates, but they are in a format that will be interpreted as floats (e.g.&nbsp;20007.08). Here we change them to datetimes and use them to set the index, giving us a DateTime index.</p>
<p>Earlier we mentioned methods, and we saw that strings have method <code>split()</code> which splits the string. Columns in Pandas that are of the type <code>str</code>, that is to say string, have all of the same methods under an attribute called <code>str</code>.</p>
<p>This cell uses many methods strung together to change the Period column to DateTime format and set the index.</p>
<div id="a0b52fc2" class="cell columns column-output-location" data-execution_count="21">
<div class="column">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a></a>df.index <span class="op">=</span> pd.to_datetime(</span>
<span id="cb40-2"><a></a>  df.Period.astype(<span class="st">'str'</span>).<span class="bu">str</span>.split(<span class="st">'.'</span>).<span class="bu">str</span>.join(<span class="st">'-'</span>)</span>
<span id="cb40-3"><a></a>)</span>
<span id="cb40-4"><a></a></span>
<span id="cb40-5"><a></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="21">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Anzsic</th>
<th data-quarto-table-cell-role="th">Anzsic_descriptor</th>
<th data-quarto-table-cell-role="th">Gas</th>
<th data-quarto-table-cell-role="th">Period</th>
<th data-quarto-table-cell-role="th">Data_value</th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Units</th>
<th data-quarto-table-cell-role="th">Magnitude</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Period</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2010-03-01</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.03</td>
<td>10875</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2010-06-01</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.06</td>
<td>11003</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2010-09-01</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.09</td>
<td>10993</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2010-12-01</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2010.12</td>
<td>10914</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2011-03-01</td>
<td>AAZ</td>
<td>Agriculture, forestry, fishing</td>
<td>Carbon dioxide equivalents</td>
<td>2011.03</td>
<td>11014</td>
<td>Seasonally adjusted</td>
<td>Kilotonnes</td>
<td>Carbon dioxide equivalents</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></div>
<p>See what gasses are measured by looking at unique values in the Gas column.</p>
<div id="1757dabf" class="cell columns column-output-location" data-execution_count="22">
<div class="column">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a></a>df.Gas.unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>array(['Carbon dioxide equivalents', 'Methane', 'Carbon dioxide',
       'Fluorinated gases', 'Nitrous oxide'], dtype=object)</code></pre>
</div>
</div></div>
<div id="ad2ee9ab" class="cell columns column-output-location" data-execution_count="23">
<div class="column">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb43-2"><a></a></span>
<span id="cb43-3"><a></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>)</span>
<span id="cb43-4"><a></a></span>
<span id="cb43-5"><a></a>df[(df.index.month <span class="op">==</span> <span class="dv">6</span>) <span class="op">&amp;</span></span>
<span id="cb43-6"><a></a>  (df.Gas <span class="op">==</span> <span class="st">'Nitrous oxide'</span>) <span class="op">&amp;</span></span>
<span id="cb43-7"><a></a>  (df.Anzsic <span class="op">==</span> <span class="st">'ZZZ'</span>)</span>
<span id="cb43-8"><a></a>].plot.scatter(<span class="st">'Period'</span>, <span class="st">'Data_value'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb43-9"><a></a>ax.set_title(<span class="st">'NZ June Nitrous Oxide Emissions'</span>)</span>
<span id="cb43-10"><a></a>ax.set_ylabel(<span class="st">'Kilotonnes'</span>)</span>
<span id="cb43-11"><a></a>ax.set_xlabel(<span class="st">'Year'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>Text(0.5, 0, 'Year')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="python_geospatial_basics_files/figure-revealjs/cell-24-output-2.png" width="825" height="449"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section id="pandas-dataframe-cont." class="slide level2 scrollable">
<h2>Pandas DataFrame Cont.</h2>
<p>There is a lot more to know about Pandas DataFrames. This is enough for us to move on to GeoPandas. I encourage you to <a href="https://pandas.pydata.org/docs/user_guide/10min.html">learn more about Pandas</a> as an exercise.</p>
</section></section>
<section>
<section id="exploring-vector-data-with-geopandas" class="title-slide slide level1 center" data-background-image="images/pandas.png">
<h1>Exploring Vector Data with Geopandas</h1>

</section>
<section id="geopandas" class="slide level2" data-background-image="images/pandas.png">
<h2>Geopandas</h2>
</section>
<section id="vector-data" class="slide level2 smaller">
<h2>Vector Data</h2>
<ul>
<li>Most often we will interact with vector data using <a href="https://geopandas.org/en/stable/">GeoPandas</a>
<ul>
<li>GeoPandas is an extension of <a href="https://pandas.pydata.org/">Pandas</a>.</li>
<li>It uses Fiona, which in-turn relies on <a href="https://gdal.org/en/stable/">GDAL and OGR</a>, to read and write.</li>
<li>Vector data is handled by the <a href="http://toblerity.org/shapely/manual.html">Shapely</a> module, which relies on <a href="https://libgeos.org/">GEOS</a>.</li>
<li>GEOS implements the <a href="https://en.wikipedia.org/wiki/Open_Geospatial_Consortium">OGC</a> <a href="https://en.wikipedia.org/wiki/Simple_Features">Simple Features geometry</a></li>
</ul></li>
<li>Projections are managed by <a href="https://pyproj4.github.io/pyproj/stable/">pyproj</a> which is built upon <a href="https://proj.org/en/stable/">PROJ</a></li>
</ul>
</section>
<section id="shapely" class="slide level2 smaller">
<h2>Shapely</h2>
<ul>
<li>Shapely Geometric Objects consist of coordinate tuples:
<ul>
<li>Point - (x, y) or three dimensional (x, y, z), e.g.&nbsp;<code>Point(5.2, 52.1)</code></li>
<li>LineString - List if coordinates of vertices, e.g.&nbsp;<code>LineString([(0, 0), (1, 2)])</code></li>
<li>Polygon - Basically a closed linestring, e.g.&nbsp;<code>Polygon(((0., 0.), (0., 1.), (1., 1.), (1., 0.), (0., 0.)))</code></li>
<li>Notice that the first and last coord of the Polygon are the same.</li>
<li>More on <a href="https://shapely.readthedocs.io/en/stable/geometry.html">Shapely geometries</a></li>
</ul></li>
</ul>
</section>
<section id="polygon" class="slide level2">
<h2>Polygon</h2>
<div id="5eb4463c" class="cell columns column-output-location" data-execution_count="24">
<div class="column">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a></a><span class="im">from</span> shapely <span class="im">import</span> Polygon</span>
<span id="cb45-2"><a></a></span>
<span id="cb45-3"><a></a>coords <span class="op">=</span> ((<span class="fl">0.</span>, <span class="fl">0.</span>), (<span class="fl">0.</span>, <span class="fl">2.</span>), (<span class="fl">1.</span>, <span class="fl">1.</span>), (<span class="fl">1.</span>, <span class="fl">0.</span>), (<span class="fl">0.</span>, <span class="fl">0.</span>))</span>
<span id="cb45-4"><a></a>p <span class="op">=</span> Polygon(coords)</span>
<span id="cb45-5"><a></a></span>
<span id="cb45-6"><a></a>c <span class="op">=</span> p.exterior.coords</span>
<span id="cb45-7"><a></a></span>
<span id="cb45-8"><a></a><span class="bu">print</span>(c[<span class="dv">0</span>] <span class="op">==</span> c[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb45-9"><a></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>True</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="24">
<div>
<figure>
<p><img data-src="python_geospatial_basics_files/figure-revealjs/cell-25-output-2.svg"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section id="reading-files" class="slide level2">
<h2>Reading Files</h2>
<p>Here we will read a geojson using the <code>read_file</code> method.</p>
<div id="75cb576d" class="cell columns column-output-location" data-execution_count="25">
<div class="column">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb47-2"><a></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb47-3"><a></a></span>
<span id="cb47-4"><a></a><span class="co"># path to data</span></span>
<span id="cb47-5"><a></a>data_dir <span class="op">=</span> Path(<span class="st">'data'</span>)</span>
<span id="cb47-6"><a></a>geojson <span class="op">=</span> data_dir <span class="op">/</span> <span class="st">'upper_santa_rita_creek.geojson'</span></span>
<span id="cb47-7"><a></a></span>
<span id="cb47-8"><a></a><span class="co"># open the geojson</span></span>
<span id="cb47-9"><a></a>gdf <span class="op">=</span> gpd.read_file(geojson)</span>
<span id="cb47-10"><a></a></span>
<span id="cb47-11"><a></a>gdf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="25">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>globalwatershedpoint</td>
<td>POINT (-120.80331 35.52537)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>globalwatershed</td>
<td>POLYGON ((-120.81096 35.50944, -120.81161 35.5...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></div>
<div id="d12d145e" class="cell columns column-output-location" data-execution_count="26">
<div class="column">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb48-2"><a></a><span class="im">import</span> contextily <span class="im">as</span> cx</span>
<span id="cb48-3"><a></a></span>
<span id="cb48-4"><a></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb48-5"><a></a>gdf.to_crs(epsg<span class="op">=</span><span class="dv">3857</span>).plot(</span>
<span id="cb48-6"><a></a>  edgecolor<span class="op">=</span><span class="st">'r'</span>,</span>
<span id="cb48-7"><a></a>  ax<span class="op">=</span>ax,</span>
<span id="cb48-8"><a></a>  facecolor<span class="op">=</span><span class="st">'none'</span>)</span>
<span id="cb48-9"><a></a>cx.add_basemap(</span>
<span id="cb48-10"><a></a>  ax<span class="op">=</span>ax,</span>
<span id="cb48-11"><a></a>  source<span class="op">=</span>cx.providers.USGS.USImageryTopo</span>
<span id="cb48-12"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="python_geospatial_basics_files/figure-revealjs/cell-27-output-1.png" width="811" height="573"></p>
</figure>
</div>
</div>
</div></div>
<div id="592aff20" class="cell columns column-output-location" data-execution_count="27">
<div class="column">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a></a><span class="im">import</span> geodatasets</span>
<span id="cb49-2"><a></a>chicago <span class="op">=</span> gpd.read_file(geodatasets.get_path(<span class="st">'geoda.chicago_commpop'</span>))</span>
<span id="cb49-3"><a></a>chicago.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="27">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">community</th>
<th data-quarto-table-cell-role="th">NID</th>
<th data-quarto-table-cell-role="th">POP2010</th>
<th data-quarto-table-cell-role="th">POP2000</th>
<th data-quarto-table-cell-role="th">POPCH</th>
<th data-quarto-table-cell-role="th">POPPERCH</th>
<th data-quarto-table-cell-role="th">popplus</th>
<th data-quarto-table-cell-role="th">popneg</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>DOUGLAS</td>
<td>35</td>
<td>18238</td>
<td>26470</td>
<td>-8232</td>
<td>-31.099358</td>
<td>0</td>
<td>1</td>
<td>MULTIPOLYGON (((-87.60914 41.84469, -87.60915 ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>OAKLAND</td>
<td>36</td>
<td>5918</td>
<td>6110</td>
<td>-192</td>
<td>-3.142390</td>
<td>0</td>
<td>1</td>
<td>MULTIPOLYGON (((-87.59215 41.81693, -87.59231 ...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>FULLER PARK</td>
<td>37</td>
<td>2876</td>
<td>3420</td>
<td>-544</td>
<td>-15.906433</td>
<td>0</td>
<td>1</td>
<td>MULTIPOLYGON (((-87.6288 41.80189, -87.62879 4...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>GRAND BOULEVARD</td>
<td>38</td>
<td>21929</td>
<td>28006</td>
<td>-6077</td>
<td>-21.698922</td>
<td>0</td>
<td>1</td>
<td>MULTIPOLYGON (((-87.60671 41.81681, -87.6067 4...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>KENWOOD</td>
<td>39</td>
<td>17841</td>
<td>18363</td>
<td>-522</td>
<td>-2.842673</td>
<td>0</td>
<td>1</td>
<td>MULTIPOLYGON (((-87.59215 41.81693, -87.59215 ...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></div>
<p>Plot Cloropleth</p>
<div id="13688342" class="cell columns column-output-location" data-execution_count="28">
<div class="column">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a></a>chicago.plot(column<span class="op">=</span><span class="st">"POP2010"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="python_geospatial_basics_files/figure-revealjs/cell-29-output-1.png" width="369" height="411"></p>
</figure>
</div>
</div>
</div></div>
<p>The Chicago example is taken from <a href="https://geopandas.org/en/stable/docs/user_guide/mapping.html">GeoPandas Mapping and plotting tools</a> tutorial, which you should take a look at.</p>
</section></section>
<section>
<section id="working-with-rasters-in-python" class="title-slide slide level1 center">
<h1>Working with Rasters in Python</h1>

</section>
<section id="rioxarray" class="slide level2">
<h2>rioXarray</h2>
</section>
<section id="working-with-climate-data-with-rioxarray" class="slide level2">
<h2>Working with Climate data with rioXarray</h2>
<p>In this tutorial we will be looking at sea surface temaperatures using Community Earth System Model 2 (CESM2) data. This tutorial borrows heavily from <a href="https://comptools.climatematch.io/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial5.html">this tutorial</a> by Computational Tools in Climate Science.</p>
<p>First import libraries and download dataset.</p>
<div id="6420aff5" class="cell columns column-output-location" data-execution_count="29">
<div class="column">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb51-2"><a></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb51-3"><a></a><span class="im">import</span> xarray <span class="im">as</span> xr</span>
<span id="cb51-4"><a></a><span class="im">from</span> pythia_datasets <span class="im">import</span> DATASETS</span>
<span id="cb51-5"><a></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb51-6"><a></a></span>
<span id="cb51-7"><a></a></span>
<span id="cb51-8"><a></a>filepath <span class="op">=</span> DATASETS.fetch(<span class="st">'CESM2_sst_data.nc'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">

</div></div>
<p>Open the dataset and inspect.</p>
<div id="cb34e3d0" class="cell columns column-output-location" data-execution_count="30">
<div class="column">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a></a>ds <span class="op">=</span> xr.open_dataset(filepath)</span>
<span id="cb52-2"><a></a>ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div><div class="column">
<div class="cell-output cell-output-display" data-execution_count="30">
<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
html[data-theme=dark],
body[data-theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block !important;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 0 20px 0 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: inline-block;
  opacity: 0;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:focus + label {
  border: 2px solid var(--xr-font-color0);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-index-preview {
  grid-column: 2 / 5;
  color: var(--xr-font-color2);
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data,
.xr-index-data-in:checked ~ .xr-index-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-index-name div,
.xr-index-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2,
.xr-no-icon {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt; Size: 47MB
Dimensions:    (time: 180, d2: 2, lat: 180, lon: 360)
Coordinates:
  * time       (time) object 1kB 2000-01-15 12:00:00 ... 2014-12-15 12:00:00
  * lat        (lat) float64 1kB -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
  * lon        (lon) float64 3kB 0.5 1.5 2.5 3.5 4.5 ... 356.5 357.5 358.5 359.5
Dimensions without coordinates: d2
Data variables:
    time_bnds  (time, d2) object 3kB ...
    lat_bnds   (lat, d2) float64 3kB ...
    lon_bnds   (lon, d2) float64 6kB ...
    tos        (time, lat, lon) float32 47MB ...
Attributes: (12/45)
    Conventions:            CF-1.7 CMIP-6.2
    activity_id:            CMIP
    branch_method:          standard
    branch_time_in_child:   674885.0
    branch_time_in_parent:  219000.0
    case_id:                972
    ...                     ...
    sub_experiment_id:      none
    table_id:               Omon
    tracking_id:            hdl:21.14100/2975ffd3-1d7b-47e3-961a-33f212ea4eb2
    variable_id:            tos
    variant_info:           CMIP6 20th century experiments (1850-2014) with C...
    variant_label:          r11i1p1f1</pre><div class="xr-wrap" style="display:none"><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-b11dc4d7-c821-4af6-a21a-39507d7056da" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-b11dc4d7-c821-4af6-a21a-39507d7056da" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span class="xr-has-index">time</span>: 180</li><li><span>d2</span>: 2</li><li><span class="xr-has-index">lat</span>: 180</li><li><span class="xr-has-index">lon</span>: 360</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-c878acf5-7e05-45ce-92d9-7be7c6024807" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-c878acf5-7e05-45ce-92d9-7be7c6024807" class="xr-section-summary">Coordinates: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">time</span></div><div class="xr-var-dims">(time)</div><div class="xr-var-dtype">object</div><div class="xr-var-preview xr-preview">2000-01-15 12:00:00 ... 2014-12-...</div><input id="attrs-c5fcc242-c0b9-48e2-ad91-ae43f7c0eecc" class="xr-var-attrs-in" type="checkbox"><label for="attrs-c5fcc242-c0b9-48e2-ad91-ae43f7c0eecc" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-8bfda58e-7e9a-4d80-a990-712416257ac9" class="xr-var-data-in" type="checkbox"><label for="data-8bfda58e-7e9a-4d80-a990-712416257ac9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>axis :</span></dt><dd>T</dd><dt><span>bounds :</span></dt><dd>time_bnds</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>title :</span></dt><dd>time</dd><dt><span>type :</span></dt><dd>double</dd></dl></div><div class="xr-var-data"><pre>array([cftime.DatetimeNoLeap(2000, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2000, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2001, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2002, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2003, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2004, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2005, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2006, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2007, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2008, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2009, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2010, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2011, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2012, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2013, 12, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 1, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 2, 14, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 3, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 4, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 5, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 6, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 7, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 8, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 9, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 10, 15, 12, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 11, 15, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 12, 15, 12, 0, 0, 0, has_year_zero=True)],
      dtype=object)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">lat</span></div><div class="xr-var-dims">(lat)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">-89.5 -88.5 -87.5 ... 88.5 89.5</div><input id="attrs-a9b60861-2537-41ae-8007-4dc50f3cbdc6" class="xr-var-attrs-in" type="checkbox"><label for="attrs-a9b60861-2537-41ae-8007-4dc50f3cbdc6" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-ddd8f7e8-2ece-4df9-9e0f-98604e6ae221" class="xr-var-data-in" type="checkbox"><label for="data-ddd8f7e8-2ece-4df9-9e0f-98604e6ae221" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>axis :</span></dt><dd>Y</dd><dt><span>bounds :</span></dt><dd>lat_bnds</dd><dt><span>long_name :</span></dt><dd>latitude</dd><dt><span>standard_name :</span></dt><dd>latitude</dd><dt><span>units :</span></dt><dd>degrees_north</dd></dl></div><div class="xr-var-data"><pre>array([-89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5, -80.5,
       -79.5, -78.5, -77.5, -76.5, -75.5, -74.5, -73.5, -72.5, -71.5, -70.5,
       -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.5, -62.5, -61.5, -60.5,
       -59.5, -58.5, -57.5, -56.5, -55.5, -54.5, -53.5, -52.5, -51.5, -50.5,
       -49.5, -48.5, -47.5, -46.5, -45.5, -44.5, -43.5, -42.5, -41.5, -40.5,
       -39.5, -38.5, -37.5, -36.5, -35.5, -34.5, -33.5, -32.5, -31.5, -30.5,
       -29.5, -28.5, -27.5, -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5,
       -19.5, -18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,
        -9.5,  -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,  -1.5,  -0.5,
         0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,   9.5,
        10.5,  11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,  18.5,  19.5,
        20.5,  21.5,  22.5,  23.5,  24.5,  25.5,  26.5,  27.5,  28.5,  29.5,
        30.5,  31.5,  32.5,  33.5,  34.5,  35.5,  36.5,  37.5,  38.5,  39.5,
        40.5,  41.5,  42.5,  43.5,  44.5,  45.5,  46.5,  47.5,  48.5,  49.5,
        50.5,  51.5,  52.5,  53.5,  54.5,  55.5,  56.5,  57.5,  58.5,  59.5,
        60.5,  61.5,  62.5,  63.5,  64.5,  65.5,  66.5,  67.5,  68.5,  69.5,
        70.5,  71.5,  72.5,  73.5,  74.5,  75.5,  76.5,  77.5,  78.5,  79.5,
        80.5,  81.5,  82.5,  83.5,  84.5,  85.5,  86.5,  87.5,  88.5,  89.5])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">lon</span></div><div class="xr-var-dims">(lon)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">0.5 1.5 2.5 ... 357.5 358.5 359.5</div><input id="attrs-3d6eee1b-76d9-4e63-8a8d-a41fb514839f" class="xr-var-attrs-in" type="checkbox"><label for="attrs-3d6eee1b-76d9-4e63-8a8d-a41fb514839f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c3101f57-575e-485e-83f6-de9dcbac5ad4" class="xr-var-data-in" type="checkbox"><label for="data-c3101f57-575e-485e-83f6-de9dcbac5ad4" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>axis :</span></dt><dd>X</dd><dt><span>bounds :</span></dt><dd>lon_bnds</dd><dt><span>long_name :</span></dt><dd>longitude</dd><dt><span>standard_name :</span></dt><dd>longitude</dd><dt><span>units :</span></dt><dd>degrees_east</dd></dl></div><div class="xr-var-data"><pre>array([  0.5,   1.5,   2.5, ..., 357.5, 358.5, 359.5])</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-4bd3317a-a882-4b5d-8ccc-fe8595cebd68" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-4bd3317a-a882-4b5d-8ccc-fe8595cebd68" class="xr-section-summary">Data variables: <span>(4)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>time_bnds</span></div><div class="xr-var-dims">(time, d2)</div><div class="xr-var-dtype">object</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-31c57679-a712-4cdf-9f1f-b523fbba8edb" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-31c57679-a712-4cdf-9f1f-b523fbba8edb" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-2ccd3029-498d-48e6-afca-e622d7565112" class="xr-var-data-in" type="checkbox"><label for="data-2ccd3029-498d-48e6-afca-e622d7565112" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>[360 values with dtype=object]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>lat_bnds</span></div><div class="xr-var-dims">(lat, d2)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-f696d03f-8fcf-4cbb-bdaf-0a2f1650a19a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-f696d03f-8fcf-4cbb-bdaf-0a2f1650a19a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-b4151039-5332-4638-bee3-fd6cf4e8bfc7" class="xr-var-data-in" type="checkbox"><label for="data-b4151039-5332-4638-bee3-fd6cf4e8bfc7" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>latitude bounds</dd><dt><span>units :</span></dt><dd>degrees_north</dd></dl></div><div class="xr-var-data"><pre>[360 values with dtype=float64]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>lon_bnds</span></div><div class="xr-var-dims">(lon, d2)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-ef5b76c2-07cc-419a-97c8-377059abab67" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ef5b76c2-07cc-419a-97c8-377059abab67" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-d69e1d97-7c08-4a9f-bf7c-48680663faf8" class="xr-var-data-in" type="checkbox"><label for="data-d69e1d97-7c08-4a9f-bf7c-48680663faf8" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>longitude bounds</dd><dt><span>units :</span></dt><dd>degrees_east</dd></dl></div><div class="xr-var-data"><pre>[720 values with dtype=float64]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>tos</span></div><div class="xr-var-dims">(time, lat, lon)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-d9a50530-c438-4aa7-a6bb-3aba40b0b5de" class="xr-var-attrs-in" type="checkbox"><label for="attrs-d9a50530-c438-4aa7-a6bb-3aba40b0b5de" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-14cf5592-a456-4db2-bcda-f006a98bce12" class="xr-var-data-in" type="checkbox"><label for="data-14cf5592-a456-4db2-bcda-f006a98bce12" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>cell_measures :</span></dt><dd>area: areacello</dd><dt><span>cell_methods :</span></dt><dd>area: mean where sea time: mean</dd><dt><span>comment :</span></dt><dd>Model data on the 1x1 grid includes values in all cells for which ocean cells on the native grid cover more than 52.5 percent of the 1x1 grid cell. This 52.5 percent cutoff was chosen to produce ocean surface area on the 1x1 grid as close as possible to ocean surface area on the native grid, while not introducing fractional cell coverage.</dd><dt><span>description :</span></dt><dd>This may differ from "surface temperature" in regions of sea ice or floating ice shelves. For models using conservative temperature as the prognostic field, they should report the top ocean layer as surface potential temperature, which is the same as surface in situ temperature.</dd><dt><span>frequency :</span></dt><dd>mon</dd><dt><span>id :</span></dt><dd>tos</dd><dt><span>long_name :</span></dt><dd>Sea Surface Temperature</dd><dt><span>mipTable :</span></dt><dd>Omon</dd><dt><span>out_name :</span></dt><dd>tos</dd><dt><span>prov :</span></dt><dd>Omon ((isd.003))</dd><dt><span>realm :</span></dt><dd>ocean</dd><dt><span>standard_name :</span></dt><dd>sea_surface_temperature</dd><dt><span>time :</span></dt><dd>time</dd><dt><span>time_label :</span></dt><dd>time-mean</dd><dt><span>time_title :</span></dt><dd>Temporal mean</dd><dt><span>title :</span></dt><dd>Sea Surface Temperature</dd><dt><span>type :</span></dt><dd>real</dd><dt><span>units :</span></dt><dd>degC</dd><dt><span>variable_id :</span></dt><dd>tos</dd></dl></div><div class="xr-var-data"><pre>[11664000 values with dtype=float32]</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-06be9ac6-4867-49e1-91d9-bd6bfe0f256b" class="xr-section-summary-in" type="checkbox"><label for="section-06be9ac6-4867-49e1-91d9-bd6bfe0f256b" class="xr-section-summary">Indexes: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-index-name"><div>time</div></div><div class="xr-index-preview">PandasIndex</div><div></div><input id="index-9043c458-2171-478f-805d-4190c4be93ad" class="xr-index-data-in" type="checkbox"><label for="index-9043c458-2171-478f-805d-4190c4be93ad" title="Show/Hide index repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-index-data"><pre>PandasIndex(CFTimeIndex([2000-01-15 12:00:00, 2000-02-14 00:00:00, 2000-03-15 12:00:00,
             2000-04-15 00:00:00, 2000-05-15 12:00:00, 2000-06-15 00:00:00,
             2000-07-15 12:00:00, 2000-08-15 12:00:00, 2000-09-15 00:00:00,
             2000-10-15 12:00:00,
             ...
             2014-03-15 12:00:00, 2014-04-15 00:00:00, 2014-05-15 12:00:00,
             2014-06-15 00:00:00, 2014-07-15 12:00:00, 2014-08-15 12:00:00,
             2014-09-15 00:00:00, 2014-10-15 12:00:00, 2014-11-15 00:00:00,
             2014-12-15 12:00:00],
            dtype='object', length=180, calendar='noleap', freq=None))</pre></div></li><li class="xr-var-item"><div class="xr-index-name"><div>lat</div></div><div class="xr-index-preview">PandasIndex</div><div></div><input id="index-6d819dff-129e-4147-88d4-66d42484af99" class="xr-index-data-in" type="checkbox"><label for="index-6d819dff-129e-4147-88d4-66d42484af99" title="Show/Hide index repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-index-data"><pre>PandasIndex(Index([-89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5, -80.5,
       ...
        80.5,  81.5,  82.5,  83.5,  84.5,  85.5,  86.5,  87.5,  88.5,  89.5],
      dtype='float64', name='lat', length=180))</pre></div></li><li class="xr-var-item"><div class="xr-index-name"><div>lon</div></div><div class="xr-index-preview">PandasIndex</div><div></div><input id="index-9293d00f-19da-4e1b-8109-a168fba1b775" class="xr-index-data-in" type="checkbox"><label for="index-9293d00f-19da-4e1b-8109-a168fba1b775" title="Show/Hide index repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-index-data"><pre>PandasIndex(Index([  0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,   9.5,
       ...
       350.5, 351.5, 352.5, 353.5, 354.5, 355.5, 356.5, 357.5, 358.5, 359.5],
      dtype='float64', name='lon', length=360))</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-968bbd03-a9f5-45d4-97ea-2b3bb5de66aa" class="xr-section-summary-in" type="checkbox"><label for="section-968bbd03-a9f5-45d4-97ea-2b3bb5de66aa" class="xr-section-summary">Attributes: <span>(45)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>Conventions :</span></dt><dd>CF-1.7 CMIP-6.2</dd><dt><span>activity_id :</span></dt><dd>CMIP</dd><dt><span>branch_method :</span></dt><dd>standard</dd><dt><span>branch_time_in_child :</span></dt><dd>674885.0</dd><dt><span>branch_time_in_parent :</span></dt><dd>219000.0</dd><dt><span>case_id :</span></dt><dd>972</dd><dt><span>cesm_casename :</span></dt><dd>b.e21.BHIST.f09_g17.CMIP6-historical.011</dd><dt><span>contact :</span></dt><dd>cesm_cmip6@ucar.edu</dd><dt><span>creation_date :</span></dt><dd>2019-04-02T04:44:58Z</dd><dt><span>data_specs_version :</span></dt><dd>01.00.29</dd><dt><span>experiment :</span></dt><dd>Simulation of recent past (1850 to 2014). Impose changing conditions (consistent with observations). Should be initialised from a point early enough in the pre-industrial control run to ensure that the end of all the perturbed runs branching from the end of this historical run end before the end of the control. Only one ensemble member is requested but modelling groups are strongly encouraged to submit at least three ensemble members of their CMIP historical simulation. </dd><dt><span>experiment_id :</span></dt><dd>historical</dd><dt><span>external_variables :</span></dt><dd>areacello</dd><dt><span>forcing_index :</span></dt><dd>1</dd><dt><span>frequency :</span></dt><dd>mon</dd><dt><span>further_info_url :</span></dt><dd>https://furtherinfo.es-doc.org/CMIP6.NCAR.CESM2.historical.none.r11i1p1f1</dd><dt><span>grid :</span></dt><dd>ocean data regridded from native gx1v7 displaced pole grid (384x320 latxlon) to 180x360 latxlon using conservative regridding</dd><dt><span>grid_label :</span></dt><dd>gr</dd><dt><span>initialization_index :</span></dt><dd>1</dd><dt><span>institution :</span></dt><dd>National Center for Atmospheric Research, Climate and Global Dynamics Laboratory, 1850 Table Mesa Drive, Boulder, CO 80305, USA</dd><dt><span>institution_id :</span></dt><dd>NCAR</dd><dt><span>license :</span></dt><dd>CMIP6 model data produced by &lt;The National Center for Atmospheric Research&gt; is licensed under a Creative Commons Attribution-[]ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file)[]. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.</dd><dt><span>mip_era :</span></dt><dd>CMIP6</dd><dt><span>model_doi_url :</span></dt><dd>https://doi.org/10.5065/D67H1H0V</dd><dt><span>nominal_resolution :</span></dt><dd>1x1 degree</dd><dt><span>parent_activity_id :</span></dt><dd>CMIP</dd><dt><span>parent_experiment_id :</span></dt><dd>piControl</dd><dt><span>parent_mip_era :</span></dt><dd>CMIP6</dd><dt><span>parent_source_id :</span></dt><dd>CESM2</dd><dt><span>parent_time_units :</span></dt><dd>days since 0001-01-01 00:00:00</dd><dt><span>parent_variant_label :</span></dt><dd>r1i1p1f1</dd><dt><span>physics_index :</span></dt><dd>1</dd><dt><span>product :</span></dt><dd>model-output</dd><dt><span>realization_index :</span></dt><dd>11</dd><dt><span>realm :</span></dt><dd>ocean</dd><dt><span>source :</span></dt><dd>CESM2 (2017): atmosphere: CAM6 (0.9x1.25 finite volume grid; 288 x 192 longitude/latitude; 32 levels; top level 2.25 mb); ocean: POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m); sea_ice: CICE5.1 (same grid as ocean); land: CLM5 0.9x1.25 finite volume grid; 288 x 192 longitude/latitude; 32 levels; top level 2.25 mb); aerosol: MAM4 (0.9x1.25 finite volume grid; 288 x 192 longitude/latitude; 32 levels; top level 2.25 mb); atmoschem: MAM4 (0.9x1.25 finite volume grid; 288 x 192 longitude/latitude; 32 levels; top level 2.25 mb); landIce: CISM2.1; ocnBgchem: MARBL (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)</dd><dt><span>source_id :</span></dt><dd>CESM2</dd><dt><span>source_type :</span></dt><dd>AOGCM BGC</dd><dt><span>sub_experiment :</span></dt><dd>none</dd><dt><span>sub_experiment_id :</span></dt><dd>none</dd><dt><span>table_id :</span></dt><dd>Omon</dd><dt><span>tracking_id :</span></dt><dd>hdl:21.14100/2975ffd3-1d7b-47e3-961a-33f212ea4eb2</dd><dt><span>variable_id :</span></dt><dd>tos</dd><dt><span>variant_info :</span></dt><dd>CMIP6 20th century experiments (1850-2014) with CAM6, interactive land (CLM5), coupled ocean (POP2) with biogeochemistry (MARBL), interactive sea ice (CICE5.1), and non-evolving land ice (CISM2.1)</dd><dt><span>variant_label :</span></dt><dd>r11i1p1f1</dd></dl></div></li></ul></div></div>
</div>
</div></div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>